### ISSUE TITLE
maybe specify a custom key-value "command"?

### ISSUE THREAD

**Issue by timo** [cygx/p6-image-rgba-text#4]
I'm experimenting with heredocs in perl6 code turning into images to be used in an SDL2 project, for example as spritesheets.

For this purpose it could be nice to have not only the info string that's decidedly free-form, but also some key-value properties that the library would parse by itself. Does that sound sensible?

**Comment by cygx** [comment]
How does something like

    =meta author timotimo
    =meta date 2019-02-07

that gets stored in a hash sound to you?

**Comment by cygx** [comment]
Cf https://github.com/cygx/p6-image-rgba-text/compare/meta

**Comment by timo** [comment]
I like it!
